#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.elf.C674{1,0,8.1,3
#
dss_mmw.xe674: package/cfg/dss_mmw.xe674.mak

clean::
	-$(RM) package/cfg/dss_mmw.xe674.mak
