#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.R4F{1,0,16.9,1
#
mss_mmw.xer4f: package/cfg/mss_mmw.xer4f.mak

clean::
	-$(RM) package/cfg/mss_mmw.xer4f.mak
